---
- name: Drop mariadb user
  community.mysql.mysql_user:
    login_host: 127.0.0.1
    login_user: root
    login_password: "{{ lookup('hashi_vault', 'secret=secret/ssh/eingram:ssh_password') }}"
    state: absent
    name: "{{ mariadb_user }}"
    host: '%'
