- name: Create postgres user
  community.postgresql.postgresql_user:
    connect_params:
      target_session_attrs: read-write
      connect_timeout: 10
    login_host: "postgres.local.lan"
    login_user: "admin"
    login_password: "{{ lookup('hashi_vault', 'secret=secret/ssh/eingram:ssh_password') }}"
    db: "{{ postgres_db }}"
    name: "{{ postgres_user }}"
    password: "{{ lookup('hashi_vault', 'secret=secret/ssh/eingram:ssh_password') }}"
    priv: ALL
